name: Robot Auto Bet261

on:
  schedule:
    # S'exécute automatiquement toutes les 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permet de cliquer sur un bouton pour tester quand tu veux

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installation des packages
        run: npm install

      - name: Lancement du Robot Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node index.js
